### ISSUE TITLE
Logo for the project

### ISSUE THREAD

**Issue by giovannipessiva** [giovannipessiva/l4w#15]
I would like to add a logo to this project.
It should contain the name "L4W", and have a pixel-art/fantasy vibe.
Preferred format is around 200x100px with transparent background (PNG or GIF), or vectorial image.
You can add the image in this path: /style/logo/
I will accept any PR for this as long as the proposed logo shows some effort (no spam please)

**Comment by nancu** [comment]
I can help with this :)
